config/routes.rb
Rails.application.routes.draw do
  resources :animals
  resources :farms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "animals#index"
end

app/models/animal.rb
class Animal < ApplicationRecord
    belongs_to :farm, dependent: :destroy
    belongs_to :farm
    def to_s
        self.name
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/farm.rb
class Farm < ApplicationRecord
    has_many :animals, dependent: :destroy
    accepts_nested_attributes_for :animals, allow_destroy: true
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: %i[ show edit update destroy ]

  # GET /animals or /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1 or /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals or /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to animal_url(@animal), notice: "Animal was successfully created." }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1 or /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to animal_url(@animal), notice: "Animal was successfully updated." }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1 or /animals/1.json
  def destroy
    @animal.destroy

    respond_to do |format|
      format.html { redirect_to animals_url, notice: "Animal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def animal_params
      params.require(:animal).permit(:name, :age, :farm_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  before_action :set_farm, only: %i[ show edit update destroy ]

  # GET /farms or /farms.json
  def index
    @farms = Farm.all
  end

  # GET /farms/1 or /farms/1.json
  def show
  end

  # GET /farms/new
  def new
    @farm = Farm.new
  end

  # GET /farms/1/edit
  def edit
  end

  # POST /farms or /farms.json
  def create
    @farm = Farm.new(farm_params)

    respond_to do |format|
      if @farm.save
        format.html { redirect_to farm_url(@farm), notice: "Farm was successfully created." }
        format.json { render :show, status: :created, location: @farm }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @farm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /farms/1 or /farms/1.json
  def update
    respond_to do |format|
      if @farm.update(farm_params)
        format.html { redirect_to farm_url(@farm), notice: "Farm was successfully updated." }
        format.json { render :show, status: :ok, location: @farm }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @farm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /farms/1 or /farms/1.json
  def destroy
    @farm.destroy

    respond_to do |format|
      format.html { redirect_to farms_url, notice: "Farm was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_farm
      @farm = Farm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def farm_params
      params.require(:farm).permit(:name)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/farms_helper.rb
module FarmsHelper
end

app/views/animals/_animal.html.erb
<div id="<%= dom_id animal %>">
  <p>
    <strong>Name:</strong>
    <%= animal.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= animal.age %>
  </p>

  <% if animal.farm %>
    <p>
      <strong>Nombre Granja:</strong>
      <%= animal.farm.name %>
    </p>
  <% end %>

</div>

app/views/animals/_form.html.erb
<%= form_with(model: animal) do |form| %>
  <% if animal.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
        <% animal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :farm_id, style: "display: block" %>
    <%= form.collection_select :farm_id, Farm.all, :id, :name, include_blank: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Editing animal</h1>

<%= render "form", animal: @animal %>

<br>

<div>
  <%= link_to "Show this animal", @animal %> |
  <%= link_to "Back to animals", animals_path %>
</div>

app/views/animals/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Animals</h1>

<div id="animals">
  <% @animals.each do |animal| %>
    <%= render animal %>
    <p>
      <%= link_to "Show this animal", animal %>
    </p>
  <% end %>
</div>

<%= link_to "New animal", new_animal_path %>

app/views/animals/new.html.erb
<h1>New animal</h1>

<%= render "form", animal: @animal %>

<br>

<div>
  <%= link_to "Back to animals", animals_path %>
</div>

app/views/animals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @animal %>

<div>
  <%= link_to "Edit this animal", edit_animal_path(@animal) %> |
  <%= link_to "Back to animals", animals_path %>

  <%= button_to "Destroy this animal", @animal, method: :delete %>
</div>

app/views/farms/_farm.html.erb
<div id="<%= dom_id farm %>">
  <p>
    <strong>Name:</strong>
    <%= farm.name %>
  </p>

</div>

app/views/farms/_form.html.erb
<%= form_with(model: farm) do |form| %>
  <% if farm.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(farm.errors.count, "error") %> prohibited this farm from being saved:</h2>

      <ul>
        <% farm.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/farms/edit.html.erb
<h1>Editing farm</h1>

<%= render "form", farm: @farm %>

<br>

<div>
  <%= link_to "Show this farm", @farm %> |
  <%= link_to "Back to farms", farms_path %>
</div>

app/views/farms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Farms</h1>

<div id="farms">
  <% @farms.each do |farm| %>
    <%= render farm %>
    <p>
      <%= link_to "Show this farm", farm %>
    </p>
  <% end %>
</div>

<%= link_to "New farm", new_farm_path %>

app/views/farms/new.html.erb
<h1>New farm</h1>

<%= render "form", farm: @farm %>

<br>

<div>
  <%= link_to "Back to farms", farms_path %>
</div>

app/views/farms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @farm %>

<div>
  <%= link_to "Edit this farm", edit_farm_path(@farm) %> |
  <%= link_to "Back to farms", farms_path %>

  <%= button_to "Destroy this farm", @farm, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Farmer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>

  <body>

  <div class="container-fluid">

    <%= yield %>

  </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>